# Generated by Django 3.2.5 on 2021-07-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.CharField(default='nil', max_length=200),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='nil', max_length=20),
        ),
    ]
