# Generated by Django 3.2.5 on 2021-07-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='Contacts',
        ),
    ]
